// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: order/order.proto

package order

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	common "github.com/xryar/golang-grpc-ecommerce/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderRequestProductItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequestProductItem) Reset() {
	*x = CreateOrderRequestProductItem{}
	mi := &file_order_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequestProductItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequestProductItem) ProtoMessage() {}

func (x *CreateOrderRequestProductItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequestProductItem.ProtoReflect.Descriptor instead.
func (*CreateOrderRequestProductItem) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequestProductItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOrderRequestProductItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	FullName      string                           `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Address       string                           `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	PhoneNumber   string                           `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Notes         string                           `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	Products      []*CreateOrderRequestProductItem `protobuf:"bytes,5,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateOrderRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateOrderRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateOrderRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *CreateOrderRequest) GetProducts() []*CreateOrderRequestProductItem {
	if x != nil {
		return x.Products
	}
	return nil
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_order_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *CreateOrderResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// List Order Admin
type ListOrderAdminRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderAdminRequest) Reset() {
	*x = ListOrderAdminRequest{}
	mi := &file_order_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderAdminRequest) ProtoMessage() {}

func (x *ListOrderAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderAdminRequest.ProtoReflect.Descriptor instead.
func (*ListOrderAdminRequest) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{3}
}

func (x *ListOrderAdminRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListOrderAdminResponseItemProducts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderAdminResponseItemProducts) Reset() {
	*x = ListOrderAdminResponseItemProducts{}
	mi := &file_order_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderAdminResponseItemProducts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderAdminResponseItemProducts) ProtoMessage() {}

func (x *ListOrderAdminResponseItemProducts) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderAdminResponseItemProducts.ProtoReflect.Descriptor instead.
func (*ListOrderAdminResponseItemProducts) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{4}
}

func (x *ListOrderAdminResponseItemProducts) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListOrderAdminResponseItemProducts) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListOrderAdminResponseItemProducts) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ListOrderAdminResponseItemProducts) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ListOrderAdminResponseItem struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Id            string                                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Number        string                                `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Customer      string                                `protobuf:"bytes,3,opt,name=customer,proto3" json:"customer,omitempty"`
	StatusCode    string                                `protobuf:"bytes,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Total         float64                               `protobuf:"fixed64,5,opt,name=total,proto3" json:"total,omitempty"`
	CreatedAt     *timestamppb.Timestamp                `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Products      []*ListOrderAdminResponseItemProducts `protobuf:"bytes,7,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderAdminResponseItem) Reset() {
	*x = ListOrderAdminResponseItem{}
	mi := &file_order_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderAdminResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderAdminResponseItem) ProtoMessage() {}

func (x *ListOrderAdminResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderAdminResponseItem.ProtoReflect.Descriptor instead.
func (*ListOrderAdminResponseItem) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{5}
}

func (x *ListOrderAdminResponseItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListOrderAdminResponseItem) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *ListOrderAdminResponseItem) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

func (x *ListOrderAdminResponseItem) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *ListOrderAdminResponseItem) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListOrderAdminResponseItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ListOrderAdminResponseItem) GetProducts() []*ListOrderAdminResponseItemProducts {
	if x != nil {
		return x.Products
	}
	return nil
}

type ListOrderAdminResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Base          *common.BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Pagination    *common.PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Items         []*ListOrderAdminResponseItem `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderAdminResponse) Reset() {
	*x = ListOrderAdminResponse{}
	mi := &file_order_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderAdminResponse) ProtoMessage() {}

func (x *ListOrderAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderAdminResponse.ProtoReflect.Descriptor instead.
func (*ListOrderAdminResponse) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{6}
}

func (x *ListOrderAdminResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ListOrderAdminResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListOrderAdminResponse) GetItems() []*ListOrderAdminResponseItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// List Order
type ListOrderRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderRequest) Reset() {
	*x = ListOrderRequest{}
	mi := &file_order_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderRequest) ProtoMessage() {}

func (x *ListOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderRequest.ProtoReflect.Descriptor instead.
func (*ListOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{7}
}

func (x *ListOrderRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListOrderResponseItemProducts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderResponseItemProducts) Reset() {
	*x = ListOrderResponseItemProducts{}
	mi := &file_order_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderResponseItemProducts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderResponseItemProducts) ProtoMessage() {}

func (x *ListOrderResponseItemProducts) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderResponseItemProducts.ProtoReflect.Descriptor instead.
func (*ListOrderResponseItemProducts) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{8}
}

func (x *ListOrderResponseItemProducts) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListOrderResponseItemProducts) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListOrderResponseItemProducts) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ListOrderResponseItemProducts) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ListOrderResponseItem struct {
	state            protoimpl.MessageState           `protogen:"open.v1"`
	Id               string                           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Number           string                           `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Customer         string                           `protobuf:"bytes,3,opt,name=customer,proto3" json:"customer,omitempty"`
	StatusCode       string                           `protobuf:"bytes,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Total            float64                          `protobuf:"fixed64,5,opt,name=total,proto3" json:"total,omitempty"`
	CreatedAt        *timestamppb.Timestamp           `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Products         []*ListOrderResponseItemProducts `protobuf:"bytes,7,rep,name=products,proto3" json:"products,omitempty"`
	XenditInvoiceUrl string                           `protobuf:"bytes,8,opt,name=xendit_invoice_url,json=xenditInvoiceUrl,proto3" json:"xendit_invoice_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListOrderResponseItem) Reset() {
	*x = ListOrderResponseItem{}
	mi := &file_order_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderResponseItem) ProtoMessage() {}

func (x *ListOrderResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderResponseItem.ProtoReflect.Descriptor instead.
func (*ListOrderResponseItem) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{9}
}

func (x *ListOrderResponseItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListOrderResponseItem) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *ListOrderResponseItem) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

func (x *ListOrderResponseItem) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *ListOrderResponseItem) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListOrderResponseItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ListOrderResponseItem) GetProducts() []*ListOrderResponseItemProducts {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListOrderResponseItem) GetXenditInvoiceUrl() string {
	if x != nil {
		return x.XenditInvoiceUrl
	}
	return ""
}

type ListOrderResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Base          *common.BaseResponse       `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Pagination    *common.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Items         []*ListOrderResponseItem   `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderResponse) Reset() {
	*x = ListOrderResponse{}
	mi := &file_order_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderResponse) ProtoMessage() {}

func (x *ListOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderResponse.ProtoReflect.Descriptor instead.
func (*ListOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{10}
}

func (x *ListOrderResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ListOrderResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListOrderResponse) GetItems() []*ListOrderResponseItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type DetailOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailOrderRequest) Reset() {
	*x = DetailOrderRequest{}
	mi := &file_order_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailOrderRequest) ProtoMessage() {}

func (x *DetailOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailOrderRequest.ProtoReflect.Descriptor instead.
func (*DetailOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{11}
}

func (x *DetailOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DetailOrderResponseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailOrderResponseItem) Reset() {
	*x = DetailOrderResponseItem{}
	mi := &file_order_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailOrderResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailOrderResponseItem) ProtoMessage() {}

func (x *DetailOrderResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailOrderResponseItem.ProtoReflect.Descriptor instead.
func (*DetailOrderResponseItem) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{12}
}

func (x *DetailOrderResponseItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DetailOrderResponseItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DetailOrderResponseItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *DetailOrderResponseItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type DetailOrderResponse struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	Base             *common.BaseResponse       `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Id               string                     `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Number           string                     `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	UserFullName     string                     `protobuf:"bytes,4,opt,name=user_full_name,json=userFullName,proto3" json:"user_full_name,omitempty"`
	Address          string                     `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	PhoneNumber      string                     `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Notes            string                     `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	OrderStatusCode  string                     `protobuf:"bytes,8,opt,name=order_status_code,json=orderStatusCode,proto3" json:"order_status_code,omitempty"`
	CreatedAt        *timestamppb.Timestamp     `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XenditInvoiceUrl string                     `protobuf:"bytes,10,opt,name=xendit_invoice_url,json=xenditInvoiceUrl,proto3" json:"xendit_invoice_url,omitempty"`
	Items            []*DetailOrderResponseItem `protobuf:"bytes,11,rep,name=items,proto3" json:"items,omitempty"`
	Total            float64                    `protobuf:"fixed64,12,opt,name=total,proto3" json:"total,omitempty"`
	ExpiredAt        *timestamppb.Timestamp     `protobuf:"bytes,13,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DetailOrderResponse) Reset() {
	*x = DetailOrderResponse{}
	mi := &file_order_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailOrderResponse) ProtoMessage() {}

func (x *DetailOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailOrderResponse.ProtoReflect.Descriptor instead.
func (*DetailOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{13}
}

func (x *DetailOrderResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DetailOrderResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DetailOrderResponse) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *DetailOrderResponse) GetUserFullName() string {
	if x != nil {
		return x.UserFullName
	}
	return ""
}

func (x *DetailOrderResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DetailOrderResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *DetailOrderResponse) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *DetailOrderResponse) GetOrderStatusCode() string {
	if x != nil {
		return x.OrderStatusCode
	}
	return ""
}

func (x *DetailOrderResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DetailOrderResponse) GetXenditInvoiceUrl() string {
	if x != nil {
		return x.XenditInvoiceUrl
	}
	return ""
}

func (x *DetailOrderResponse) GetItems() []*DetailOrderResponseItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *DetailOrderResponse) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DetailOrderResponse) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

var File_order_order_proto protoreflect.FileDescriptor

const file_order_order_proto_rawDesc = "" +
	"\n" +
	"\x11order/order.proto\x12\x05order\x1a\x1acommon/base_response.proto\x1a\x17common/pagination.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"K\n" +
	"\x1dCreateOrderRequestProductItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\"\xf4\x01\n" +
	"\x12CreateOrderRequest\x12'\n" +
	"\tfull_name\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\bfullName\x12$\n" +
	"\aaddress\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\aaddress\x12-\n" +
	"\fphone_number\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\vphoneNumber\x12\x1e\n" +
	"\x05notes\x18\x04 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\x05notes\x12@\n" +
	"\bproducts\x18\x05 \x03(\v2$.order.CreateOrderRequestProductItemR\bproducts\"O\n" +
	"\x13CreateOrderResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"R\n" +
	"\x15ListOrderAdminRequest\x129\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\"z\n" +
	"\"ListOrderAdminResponseItemProducts\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\"\x99\x02\n" +
	"\x1aListOrderAdminResponseItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x12\x1a\n" +
	"\bcustomer\x18\x03 \x01(\tR\bcustomer\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\tR\n" +
	"statusCode\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x01R\x05total\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12E\n" +
	"\bproducts\x18\a \x03(\v2).order.ListOrderAdminResponseItemProductsR\bproducts\"\xb7\x01\n" +
	"\x16ListOrderAdminResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationResponseR\n" +
	"pagination\x127\n" +
	"\x05items\x18\x03 \x03(\v2!.order.ListOrderAdminResponseItemR\x05items\"M\n" +
	"\x10ListOrderRequest\x129\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\"u\n" +
	"\x1dListOrderResponseItemProducts\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\"\xbd\x02\n" +
	"\x15ListOrderResponseItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x12\x1a\n" +
	"\bcustomer\x18\x03 \x01(\tR\bcustomer\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\tR\n" +
	"statusCode\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x01R\x05total\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12@\n" +
	"\bproducts\x18\a \x03(\v2$.order.ListOrderResponseItemProductsR\bproducts\x12,\n" +
	"\x12xendit_invoice_url\x18\b \x01(\tR\x10xenditInvoiceUrl\"\xad\x01\n" +
	"\x11ListOrderResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationResponseR\n" +
	"pagination\x122\n" +
	"\x05items\x18\x03 \x03(\v2\x1c.order.ListOrderResponseItemR\x05items\"0\n" +
	"\x12DetailOrderRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x02id\"o\n" +
	"\x17DetailOrderResponseItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\"\xfc\x03\n" +
	"\x13DetailOrderResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x16\n" +
	"\x06number\x18\x03 \x01(\tR\x06number\x12$\n" +
	"\x0euser_full_name\x18\x04 \x01(\tR\fuserFullName\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12!\n" +
	"\fphone_number\x18\x06 \x01(\tR\vphoneNumber\x12\x14\n" +
	"\x05notes\x18\a \x01(\tR\x05notes\x12*\n" +
	"\x11order_status_code\x18\b \x01(\tR\x0forderStatusCode\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12,\n" +
	"\x12xendit_invoice_url\x18\n" +
	" \x01(\tR\x10xenditInvoiceUrl\x124\n" +
	"\x05items\x18\v \x03(\v2\x1e.order.DetailOrderResponseItemR\x05items\x12\x14\n" +
	"\x05total\x18\f \x01(\x01R\x05total\x129\n" +
	"\n" +
	"expired_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\texpiredAt2\xa9\x02\n" +
	"\fOrderService\x12D\n" +
	"\vCreateOrder\x12\x19.order.CreateOrderRequest\x1a\x1a.order.CreateOrderResponse\x12M\n" +
	"\x0eListOrderAdmin\x12\x1c.order.ListOrderAdminRequest\x1a\x1d.order.ListOrderAdminResponse\x12>\n" +
	"\tListOrder\x12\x17.order.ListOrderRequest\x1a\x18.order.ListOrderResponse\x12D\n" +
	"\vDetailOrder\x12\x19.order.DetailOrderRequest\x1a\x1a.order.DetailOrderResponseB1Z/github.com/xryar/golang-grpc-ecommerce/pb/orderb\x06proto3"

var (
	file_order_order_proto_rawDescOnce sync.Once
	file_order_order_proto_rawDescData []byte
)

func file_order_order_proto_rawDescGZIP() []byte {
	file_order_order_proto_rawDescOnce.Do(func() {
		file_order_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_order_proto_rawDesc), len(file_order_order_proto_rawDesc)))
	})
	return file_order_order_proto_rawDescData
}

var file_order_order_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_order_order_proto_goTypes = []any{
	(*CreateOrderRequestProductItem)(nil),      // 0: order.CreateOrderRequestProductItem
	(*CreateOrderRequest)(nil),                 // 1: order.CreateOrderRequest
	(*CreateOrderResponse)(nil),                // 2: order.CreateOrderResponse
	(*ListOrderAdminRequest)(nil),              // 3: order.ListOrderAdminRequest
	(*ListOrderAdminResponseItemProducts)(nil), // 4: order.ListOrderAdminResponseItemProducts
	(*ListOrderAdminResponseItem)(nil),         // 5: order.ListOrderAdminResponseItem
	(*ListOrderAdminResponse)(nil),             // 6: order.ListOrderAdminResponse
	(*ListOrderRequest)(nil),                   // 7: order.ListOrderRequest
	(*ListOrderResponseItemProducts)(nil),      // 8: order.ListOrderResponseItemProducts
	(*ListOrderResponseItem)(nil),              // 9: order.ListOrderResponseItem
	(*ListOrderResponse)(nil),                  // 10: order.ListOrderResponse
	(*DetailOrderRequest)(nil),                 // 11: order.DetailOrderRequest
	(*DetailOrderResponseItem)(nil),            // 12: order.DetailOrderResponseItem
	(*DetailOrderResponse)(nil),                // 13: order.DetailOrderResponse
	(*common.BaseResponse)(nil),                // 14: common.BaseResponse
	(*common.PaginationRequest)(nil),           // 15: common.PaginationRequest
	(*timestamppb.Timestamp)(nil),              // 16: google.protobuf.Timestamp
	(*common.PaginationResponse)(nil),          // 17: common.PaginationResponse
}
var file_order_order_proto_depIdxs = []int32{
	0,  // 0: order.CreateOrderRequest.products:type_name -> order.CreateOrderRequestProductItem
	14, // 1: order.CreateOrderResponse.base:type_name -> common.BaseResponse
	15, // 2: order.ListOrderAdminRequest.pagination:type_name -> common.PaginationRequest
	16, // 3: order.ListOrderAdminResponseItem.created_at:type_name -> google.protobuf.Timestamp
	4,  // 4: order.ListOrderAdminResponseItem.products:type_name -> order.ListOrderAdminResponseItemProducts
	14, // 5: order.ListOrderAdminResponse.base:type_name -> common.BaseResponse
	17, // 6: order.ListOrderAdminResponse.pagination:type_name -> common.PaginationResponse
	5,  // 7: order.ListOrderAdminResponse.items:type_name -> order.ListOrderAdminResponseItem
	15, // 8: order.ListOrderRequest.pagination:type_name -> common.PaginationRequest
	16, // 9: order.ListOrderResponseItem.created_at:type_name -> google.protobuf.Timestamp
	8,  // 10: order.ListOrderResponseItem.products:type_name -> order.ListOrderResponseItemProducts
	14, // 11: order.ListOrderResponse.base:type_name -> common.BaseResponse
	17, // 12: order.ListOrderResponse.pagination:type_name -> common.PaginationResponse
	9,  // 13: order.ListOrderResponse.items:type_name -> order.ListOrderResponseItem
	14, // 14: order.DetailOrderResponse.base:type_name -> common.BaseResponse
	16, // 15: order.DetailOrderResponse.created_at:type_name -> google.protobuf.Timestamp
	12, // 16: order.DetailOrderResponse.items:type_name -> order.DetailOrderResponseItem
	16, // 17: order.DetailOrderResponse.expired_at:type_name -> google.protobuf.Timestamp
	1,  // 18: order.OrderService.CreateOrder:input_type -> order.CreateOrderRequest
	3,  // 19: order.OrderService.ListOrderAdmin:input_type -> order.ListOrderAdminRequest
	7,  // 20: order.OrderService.ListOrder:input_type -> order.ListOrderRequest
	11, // 21: order.OrderService.DetailOrder:input_type -> order.DetailOrderRequest
	2,  // 22: order.OrderService.CreateOrder:output_type -> order.CreateOrderResponse
	6,  // 23: order.OrderService.ListOrderAdmin:output_type -> order.ListOrderAdminResponse
	10, // 24: order.OrderService.ListOrder:output_type -> order.ListOrderResponse
	13, // 25: order.OrderService.DetailOrder:output_type -> order.DetailOrderResponse
	22, // [22:26] is the sub-list for method output_type
	18, // [18:22] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_order_order_proto_init() }
func file_order_order_proto_init() {
	if File_order_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_order_proto_rawDesc), len(file_order_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_order_proto_goTypes,
		DependencyIndexes: file_order_order_proto_depIdxs,
		MessageInfos:      file_order_order_proto_msgTypes,
	}.Build()
	File_order_order_proto = out.File
	file_order_order_proto_goTypes = nil
	file_order_order_proto_depIdxs = nil
}
